[tool.black]
line-length = 99

[tool.pylint.format]
max-line-length = 99

[tool.pyright]
ignore = ["bak/"]
reportMissingImports = false

[tool.ruff]
extend-exclude = ["bak/"]
line-length = 99

[tool.yapf]
based_on_style = "pep8"
column_limit = 99

